Repository canonical/sqlair, pull requests merged in 2024-01, with the labels that each got.

#114 feat: parse slice expressions
  internal/expr/bindtypes.go
  internal/expr/expr_test.go
  internal/expr/parser.go
  internal/expr/parser_helper_test.go
Labels: Priority

#129 bugfix: Fix duplicate output error
  internal/expr/bindtypes.go
  internal/expr/expr_test.go
  internal/typeinfo/member.go
  package_test.go
Labels: Bug

#95 Improve use of go check in tests
  internal/expr/expr_test.go
  package_test.go
Labels: Polish
